import { Inter } from "next/font/google";
import "./globals.css";
import Head from "next/head"; // Import Head from next/head to manage metadata
import Header from "./components/Header/page";
import { Providers } from "./providers";
import NavbarLanding from "./components/landing/NavbarLanding";

// Create Inter instance
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "SIG - Bone Bolango",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      {/* Use Head component to manage metadata */}
      <Head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.3.0/flowbite.min.css" />
      </Head>
      {/* Navbar should be inside the body */}
      <body className={inter.className}>
        <Header />
        <Providers>{children}</Providers>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.3.0/flowbite.min.js"></script>
      </body>
    </html>
  );
}
